### ISSUE TITLE
Stuck at apple logo

### ISSUE THREAD

**Issue by byawitz** [alexpotter1/intel-nuc6i7kyk-opencore#5]
Hi and thanks for everything. 
I have done exactly as you say but the installer just stuck at apple logo. 

Thank you for this repo very much

**Comment by byawitz** [comment]
I was able to change the plist file so it show the error
This is what I got
![20200722_212350](https://user-images.githubusercontent.com/316103/88213741-cf4c4e80-cc61-11ea-9375-bffaf345f333.jpg)

Thanks

**Comment by alexpotter1** [comment]
Hi 👋

So that I have a better understanding of what's going on, I have a few questions:
- Have you tried resetting NVRAM?
- Is there compiled aml files in the ACPI folder?
- Have all of the expected kexts downloaded correctly (occasionally GitHub's API can bug out and not download the couple that are fetched from there)
- Did you enable the Intel WiFi option or leave it disabled?
- Are you trying to run Catalina or Big Sur Beta? 
  - I had a similar issue when attempting to install Big Sur Beta but haven't got a fix yet

Thanks

**Comment by byawitz** [comment]
Hi, Thanks for answering.

1. Yes.
2. Yes
3. Yes, double-checked.
4. I had, Yes.
5. Catalina latest.

**Comment by vrchlabak** [comment]
i have the same exact issue. Try to solve by simply googling the errors to no avail.
![IMG_0558](https://user-images.githubusercontent.com/7145322/88241214-51c31700-cc3e-11ea-8581-586d9c49a00c.jpeg)

Yes.
Yes
Yes
Yes on wifi
Catalina 10.15.6, latest

I will try to upload new EFI without the WIFI fix to see if that will help.

Thanks!

**Comment by vrchlabak** [comment]
Just tried without the WIFI fix. The same issue, no dice. Thanks for your help!

**Comment by vrchlabak** [comment]
Also Alex, if you figure out how to get Scull Canyon to work with Big Sur, please let me know. As far as I know, Apple changed a lot of thing in BS, but it would be awesome if you can figure it out. Thanks for all of your hard work!

**Comment by alexpotter1** [comment]
This issue generally tends to arise when the correct kexts are not present.
The kexts this machine requires are:

- Lilu
- VirtualSMC
- WhateverGreen
- AppleALC
- CPUFriend
- NVMeFix
- IntelMausiEthernet
- USBInjectAll
- IntelBluetoothFirmware
- (optional) itlwm

I just created a new USB from the latest master and was able to boot both the Catalina installer and my installation successfully, no problems.

Perhaps try reinstalling Xcode/Xcode CLI tools? Or you can always download manually, this script is just for convenience.
Sorry I can't give more help than that.

**Comment by vrchlabak** [comment]
Thanks Alex. I will look and make sure i have the right kext present. Yes, I am using your script to download them. Currently using xcode 11.6 and CLT 12 beta 3. I am running Big Sur on my Mac Pro now.

Thanks for your efforts. I will do this in the next couple hours and report back.

BTW: any plans on getting Big Sur going on the Skull Canyon?

**Comment by vrchlabak** [comment]
Looks like I am missing:

- IntelBluetoothFirmware
- (optional) itlwm

Have HXCI in addition. Could that cause the problem? I too recreated the USB just last night and that's what i got from the script. 

Thanks!



![Screen Shot 2020-08-01 at 09 49 00](https://user-images.githubusercontent.com/7145322/89106142-490bd700-d3dc-11ea-853a-4f8f3342580b.png)

**Comment by alexpotter1** [comment]
IntelBluetoothFirmware missing would cause it to fail to boot.
itlwm is optional depending on whether you said yes or no, the script will toggle its enabled state within the plist.

I know that kext is downloaded from GitHub, maybe the API timed out somewhere...
I'll have a look and see if I can make that more reliable/retry if failed

RE Big Sur Beta: Last time I tried that (around 10 days ago with the latest OpenCore at the time) it failed to boot the new KernelCollection. Forcing use of `prelinkedkernel` did get past that stage with a USB installer but still wouldn't boot, kept getting messages about `launchd` getting killed in the log. If it's an issue of kexts not being compatible yet, there's not much I can do until the developers release updated versions.

**Comment by vrchlabak** [comment]
Thanks for the quick response!! I will try to create the USB again now and if the BT kext is still missing, i will add it manually.

Thanks for the Big Sur update. Keep us posted, it's hard to go back to Catalina after you get used to the new UI!

I appreciate your work!

**Comment by vrchlabak** [comment]
So, the script is failing to download the BTF kext which would explain it missing. Also, it's missing in the Dortania kext library, I had to download it straight from here https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases/tag/1.1.1
![Screen Shot 2020-08-01 at 10 36 00](https://user-images.githubusercontent.com/7145322/89107361-70b36d00-d3e5-11ea-9863-27475a95e9cc.png)
Is that the right one? Because the install is still stuck on Apple logo :(.

I uploaded my final EFI here https://drive.google.com/drive/folders/1RK6O2k4wveUF8TxUgvMY2oulGm7G1Vwo?usp=sharing
Any chance you can take a look and see if there are any other issues? Last week, I ran the config.plist by the Sanity Checker linked on Dortania and it came with several "issues", but I figured it was due to this build being specific to this NUC.

Thanks. Please let me know.

**Comment by alexpotter1** [comment]
Thanks for the log

I know what caused the problem, I couldn't assume that `jq` would be installed to parse the download URL. It should now be fixed in 8a7cbb7

If you run the script again it _should_ now work. It wasn't booting because `itlwm.kext` failed to download, and it was set as Enabled in your `config.plist`.

**Comment by vrchlabak** [comment]
BOOM :). I will go ahead and try it again shortly. Thanks Alex!

**Comment by vrchlabak** [comment]
Also, it looks like you got Big Sur to work!! I will try that as soon as Catalina works :). Does Thunderbolt and Ethernet work on BS?

**Comment by alexpotter1** [comment]
No problem

Ethernet works
Thunderbolt sort of works...devices connected on boot should be functional, but hotplug/sleep breaks Thunderbolt completely

I don't have any TB3 devices to test with so I haven't really tried to get that working yet

**Comment by vrchlabak** [comment]
I have T3 and T2 devices (with T3 to T2 adapter). I will try and report back. I will be using the NUC headless to control T2 enclosure for media serving (actually as slave back up server) and will disable sleep, so it should work - hopefully :).

**Comment by vrchlabak** [comment]
So, successfully installed Catalina. Wi-Fi works, too. Odd thing. after install, the internal SSD's EFI folder is empty and therefore the NUC doesn't see it as bootable drive. I mounted the install USB EFI and moved it to the internal SSD's EFI. That way the NUC boots to the OC options menu and automatically loads Catalina. I am new to all of this, but would have assumed that the EFI would automatically migrate to the target internal drive during install. But I may be doing something wrong. Regardless, Catalina works great otherwise, so success :). Thank you!!!

**Comment by alexpotter1** [comment]
Yeah, you have to manually copy it over.

I don't think Apple uses the EFI System Partition for anything even for real Macs, except for occasional firmware updates?
Good to hear you've got it working. It sounds like this has been resolved.

**Comment by vrchlabak** [comment]
yes, definitely resolved. I am onto testing Thunderbolt now. Assuming the details are under PCI vs. Thunderbolt.... OR, do I need another kext?

**Comment by alexpotter1** [comment]
Thunderbolt discussion is being tracked in #6

**Comment by TurtIeSocks** [comment]
Hey guys, sorry to comment on a closed issue but I'm having a similar issue and haven't been able to resolve it. 

Specs:
Intel NUC6i7KYK
32GB RAM
1x 1TB WD Black NVME SSD

**Have you tried resetting NVRAM?**
Not seeing the option to in the opencore bootloader menu?

**Is there compiled aml files in the ACPI folder?**
Yes

**Have all of the expected kexts downloaded correctly (occasionally GitHub's API can bug out and not download the couple that are fetched from there)**
Yes, all mentioned above are present in the kext folder.

**Did you enable the Intel WiFi option or leave it disabled?**
Enabled.

**Are you trying to run Catalina or Big Sur Beta?**
Tried Catalina 10.15.7 & Big Sur Beta 11, both produce the same result of being stuck on the Apple Logo. 

Possible Issues:
- Using a USB3.0 "Pocket SSD" drive, don't currently have a 2.0 one big enough
- Using a Mojave VM & Xcode 11.3.1 to build

Other than those 2 things, I believe everything else has been pretty vanilla in terms of following the instructions here. Any thoughts?

**Comment by alexpotter1** [comment]
Hi @TurtIeSocks 

Can you boot in verbose mode (add `-v` to `boot-args` or press Cmd/Windows + V on loading the OpenCore boot selector) and post a picture of what it gets stuck on?

Thanks 😃 
Alex

**Comment by TurtIeSocks** [comment]
![IMG_20201016_135112.jpg](https://user-images.githubusercontent.com/58572875/96291902-c5af5a00-0fb6-11eb-80be-dc08b54064eb.jpg)

Sure! This is the result. Thank you for the reply :)

**Comment by alexpotter1** [comment]
No worries 

`Halting on critical error` here means there's a kext that is required by OpenCore, but is missing from the folder.
I have found that if you build the repo on Big Sur it can fail to compile the `IntelMausiEthernet` kext because of a pre-release toolchain issue, so that could be missing.

Please check the post above for the kexts that are required for the system to boot.

Thanks
Alex

**Comment by TurtIeSocks** [comment]
![image](https://user-images.githubusercontent.com/58572875/96298200-14152680-0fc0-11eb-9f34-603fd29cada7.png)
Looks like all of the above mentioned kexts are present. Building on Mojave.

**Comment by ichasecorals** [comment]
@TurtIeSocks

Check your config.plist. Maybe there’s something missing or malformed line.

**Comment by alexpotter1** [comment]
> ![image](https://user-images.githubusercontent.com/58572875/96298200-14152680-0fc0-11eb-9f34-603fd29cada7.png)
> Looks like all of the above mentioned kexts are present. Building on Mojave.

Rename `AirportItlwm.kext` to `itlwm.kext` for now

I wasn't aware it started downloading that kext instead of the original one...I'll get that changed
Raised to fix in #13

**Comment by TurtIeSocks** [comment]
Ah, good catch. Renaming alone didn't appear to fix it, but removing the kext entirely has gotten me past the Apple logo :) thanks again!

**Comment by TurtIeSocks** [comment]
Everything went smoothly for Catalina. Can confirm that the Big Sur installation also hung after trying to rename the itlwm.kext file. Works with excluding the kext entirely though.
